# Generated by Django 2.2.1 on 2019-05-07 05:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190506_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
